import sqlite3

conn=sqlite3.connect("vizsga.db")
curs=conn.cursor()
curs.execute("CREATE TABLE IF NOT EXISTS vizsgazok (azonosito INTEGER, nev TEXT, szulido INTEGER, pontszam REAL)")
#curs.execute("INSERT INTO vizsgazok VALUES (765456, 'Jane Doe', 1995, 75.4)")
#curs.execute("INSERT INTO vizsgazok VALUES (761243, 'John Doe', 1995, 70.4)")
#curs.execute("INSERT INTO vizsgazok VALUES (765456, 'Proba Elek', 1997, 50.6)")
#curs.execute("INSERT INTO vizsgazok VALUES (701346, 'Kovacs Janos', 2000, 90.4)")
#curs.execute("INSERT INTO vizsgazok VALUES (765456, 'Proba Kinga', 2001, 56.6)")

#curs.execute("SELECT * FROM vizsgazok")
#curs.execute("SELECT nev,pontszam FROM vizsgazok WHERE pontszam > 56.6")
#curs.execute("SELECT nev FROM vizsgazok WHERE nev Like 'P%'")
#curs.execute("SELECT MIN(pontszam) FROM vizsgazok")
#curs.execute("SELECT MAX(pontszam) FROM vizsgazok")
#curs.execute("SELECT AVG(pontszam) FROM vizsgazok")
#curs.execute("UPDATE vizsgazok SET nev='Kiss Jenő' WHERE RowID= 4")
#curs.execute("UPDATE vizsgazok SET szulido=2004 WHERE nev='Kiss Jenő'")
curs.execute("DELETE FROM vizsgazok WHERE RowID= 3")
curs.execute("DELETE FROM vizsgazok WHERE ROWID=4")
curs.execute("SELECT* FROM vizsgazok")
conn.commit()
print(curs.fetchall())
conn.close()
